In [1]:
import pandas as pd
import numpy as np

from generate_results import make_results_df

In [2]:
dataset = 'inconel'
transfer_dataset = 'stainless_steel'
results_dir = 'results/inc_ss/standard_loss'

df = make_results_df(dataset, transfer_dataset, results_dir)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,inconel,n/a,0.03099 (+/- 0.00000),0.03263 (+/- 0.00000),0.02565 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,inconel,from scratch,0.02295 (+/- 0.00201),0.02289 (+/- 0.00181),0.01877 (+/- 0.00230),12.9 (+/- 8.371977066380438)
TL - 1,inconel,stainless_steel,0.01331 (+/- 0.00040),0.01268 (+/- 0.00052),0.01001 (+/- 0.00056),30.2 (+/- 10.524257693538296)
TL - 2,stainless_steel,from scratch,0.06920 (+/- 0.00096),0.06775 (+/- 0.00117),0.04458 (+/- 0.00266),11.2 (+/- 8.133879763065101)
TL - 3,stainless_steel,stainless_steel,0.06823 (+/- 0.00003),0.06656 (+/- 0.00038),0.04898 (+/- 0.00060),9.1 (+/- 2.0223748416156684)

In [3]:
dataset = 'stainless_steel'
transfer_dataset = 'inconel'
results_dir = 'results/inc_ss/standard_loss'

df = make_results_df(dataset, transfer_dataset, results_dir)
df

,Forward DNN,Inverse DNN,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
Forward Model,stainless_steel,n/a,0.03392 (+/- 0.00000),0.03240 (+/- 0.00000),0.02726 (+/- 0.00000),0.0 (+/- 0.0)
TNN Standard,stainless_steel,from scratch,0.02562 (+/- 0.00073),0.02422 (+/- 0.00087),0.02059 (+/- 0.00090),15.2 (+/- 12.432216214336043)
TL - 1,stainless_steel,inconel,0.03037 (+/- 0.00038),0.02899 (+/- 0.00052),0.02511 (+/- 0.00063),28.6 (+/- 10.901376059929316)
TL - 2,inconel,from scratch,0.02477 (+/- 0.00025),0.02400 (+/- 0.00033),0.11366 (+/- 0.00339),17.2 (+/- 22.471315048301022)
TL - 3,inconel,inconel,0.03480 (+/- 0.00010),0.03455 (+/- 0.00009),0.06304 (+/- 0.00060),26.9 (+/- 8.092589202474075)