In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
dataset_name = 'inconel'
hot_start_dataset = 'stainless_steel'


df = pd.DataFrame()

df['Config'] = ['from_scratch', 'hot_start', 'hot_start', 'hot_start', 'hot_start']
df['Hot Start Type'] = ['n/a', 'partial', 'partial', 'full', 'full']
df['Layers Transferred'] = ['n/a', '1', '2', '1', '2']

result_dir = 'forwardDNN_results'
standard_path = f'{result_dir}/standard_{dataset_name}_dataset.json'
tl_1_layer_partial_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_1_layer_{hot_start_dataset}_PARTIAL_hot_start.json'
tl_2_layer_partial_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_2_layer_{hot_start_dataset}_PARTIAL_hot_start.json'
tl_1_layer_full_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_1_layer_{hot_start_dataset}_FULL_hot_start.json'
tl_2_layer_full_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_2_layer_{hot_start_dataset}_FULL_hot_start.json'

paths = [standard_path, tl_1_layer_partial_path, tl_2_layer_partial_path, tl_1_layer_full_path, tl_2_layer_full_path]

train_losses = []
val_losses = []
test_losses = []
train_std = []
val_std = []
test_std = []
epochs = []
epochs_std = []

for path in paths:

    with open(path, 'r') as f:
        data = json.load(f)

    train_losses.append(data['mean train loss'])
    val_losses.append(data['mean val loss'])
    test_losses.append(data['test loss'])
    train_std.append(data['train loss std'])
    val_std.append(data['val loss std'])
    test_std.append(data['test loss std'])
    epochs.append(data['epochs'])
    epochs_std.append(data['epochs std'])

train_col = [f'{tl:.5f} (+/- {tl_std:.5f})' for tl, tl_std in zip(train_losses, train_std)]
val_col = [f'{vl:.5f} (+/- {vl_std:.5f})' for vl, vl_std in zip(val_losses, val_std)]
test_col = [f'{tl:.5f} (+/- {tl_std:.5f})' for tl, tl_std in zip(test_losses, test_std)]
epoch_col = [f'{e} (+/- {e_std:.2f})' for e, e_std in zip(epochs, epochs_std)]

df['Train RMSE'] = train_col
df['Val RMSE'] = val_col
df['Test RMSE'] = test_col
df['Epochs'] = epoch_col

df = df.set_index('Config')

df

,Hot Start Type,Layers Transferred,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
from_scratch,n/a,n/a,0.02907 (+/- 0.00097),0.02947 (+/- 0.00074),0.02319 (+/- 0.00059),37.75 (+/- 13.16)
hot_start,partial,1,0.02740 (+/- 0.00098),0.02877 (+/- 0.00125),0.02264 (+/- 0.00119),49.0 (+/- 16.55)
hot_start,partial,2,0.02972 (+/- 0.00048),0.03087 (+/- 0.00043),0.02454 (+/- 0.00031),61.0 (+/- 14.69)
hot_start,full,1,0.02759 (+/- 0.00000),0.02845 (+/- 0.00000),0.02294 (+/- 0.00000),35.0 (+/- 0.00)
hot_start,full,2,0.03031 (+/- 0.00000),0.03144 (+/- 0.00000),0.02507 (+/- 0.00000),49.0 (+/- 0.00)

In [3]:
dataset_name = 'stainless_steel'
hot_start_dataset = 'inconel'


df = pd.DataFrame()

df['Config'] = ['from_scratch', 'hot_start', 'hot_start', 'hot_start', 'hot_start']
df['Hot Start Type'] = ['n/a', 'partial', 'partial', 'full', 'full']
df['Layers Transferred'] = ['n/a', '1', '2', '1', '2']

result_dir = 'forwardDNN_results'
standard_path = f'{result_dir}/standard_{dataset_name}_dataset.json'
tl_1_layer_partial_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_1_layer_{hot_start_dataset}_PARTIAL_hot_start.json'
tl_2_layer_partial_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_2_layer_{hot_start_dataset}_PARTIAL_hot_start.json'
tl_1_layer_full_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_1_layer_{hot_start_dataset}_FULL_hot_start.json'
tl_2_layer_full_path = f'{result_dir}/transfer_learning_{dataset_name}_dataset_2_layer_{hot_start_dataset}_FULL_hot_start.json'

paths = [standard_path, tl_1_layer_partial_path, tl_2_layer_partial_path, tl_1_layer_full_path, tl_2_layer_full_path]

train_losses = []
val_losses = []
test_losses = []
train_std = []
val_std = []
test_std = []
epochs = []
epochs_std = []

for path in paths:

    with open(path, 'r') as f:
        data = json.load(f)

    train_losses.append(data['mean train loss'])
    val_losses.append(data['mean val loss'])
    test_losses.append(data['test loss'])
    train_std.append(data['train loss std'])
    val_std.append(data['val loss std'])
    test_std.append(data['test loss std'])
    epochs.append(data['epochs'])
    epochs_std.append(data['epochs std'])

train_col = [f'{tl:.5f} (+/- {tl_std:.5f})' for tl, tl_std in zip(train_losses, train_std)]
val_col = [f'{vl:.5f} (+/- {vl_std:.5f})' for vl, vl_std in zip(val_losses, val_std)]
test_col = [f'{tl:.5f} (+/- {tl_std:.5f})' for tl, tl_std in zip(test_losses, test_std)]
epoch_col = [f'{e} (+/- {e_std:.2f})' for e, e_std in zip(epochs, epochs_std)]

df['Train RMSE'] = train_col
df['Val RMSE'] = val_col
df['Test RMSE'] = test_col
df['Epochs'] = epoch_col

df = df.set_index('Config')

df

,Hot Start Type,Layers Transferred,Train RMSE,Val RMSE,Test RMSE,Epochs
Config,,,,,,
from_scratch,n/a,n/a,0.03412 (+/- 0.00252),0.03567 (+/- 0.00494),0.03009 (+/- 0.00374),33.05 (+/- 15.78)
hot_start,partial,1,0.03062 (+/- 0.00088),0.03105 (+/- 0.00081),0.02603 (+/- 0.00066),54.4 (+/- 11.62)
hot_start,partial,2,0.03779 (+/- 0.00074),0.03921 (+/- 0.00105),0.03188 (+/- 0.00088),38.4 (+/- 8.09)
hot_start,full,1,0.03248 (+/- 0.00000),0.03293 (+/- 0.00000),0.02771 (+/- 0.00000),32.0 (+/- 0.00)
hot_start,full,2,0.03978 (+/- 0.00000),0.04097 (+/- 0.00000),0.03406 (+/- 0.00000),38.0 (+/- 0.00)